[project]
name = "homework"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "kimi-cli>=0.59",
    "pyinstaller>=6.16.0",
    "pyqt6>=6.10.0",
    "requests>=2.32.5",
    "wordcloud>=1.9.4",
]
